---
- name: Ensure we update the known_host file on the controllers
  hosts: control
  gather_facts: false

  tasks:

    - name: Ensure the Controller is in the file
      when: "'control' in group_names"
      loop: "{{ query('inventory_hostnames', 'all') }}"
      ansible.builtin.command: /usr/bin/ssh -o "StrictHostKeyChecking no" {{ item }} date
