---
- name: Ensure that root ssh login is disabled on the controller
  hosts: all

  tasks:

    - name: Disabling root login via ssh
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#PermitRootLogin yes'
        line: 'PermitRootLogin no'
            
    - name: Reloading sshd service 
      ansible.builtin.systemd:
        state: reloaded
        name: sshd.service
        enabled: yes